version: 0.2
    
phases:
  install:
    commands:
      - echo Installing app dependencies...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon ECS...
              # Docker Image Tag with Date Time & Code Buiild Resolved Source Version
        # Update Image tag in our Kubernetes Deployment Manifest        
      - echo "Update Image tag in kube-manifest..."
        # Verify AWS CLI Version        
      - echo "Verify AWS CLI Version..."
      - aws --version
        # Login to ECR Registry for docker to push the image to ECR Repository
      - echo "Login in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      # Build Docker Image
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - echo "Pushing the Docker image to ECR Repository"
      - docker push $REPOSITORY_URI:latest
  build:
    commands:
      # Extracting AWS Credential Information using STS Assume Role for kubectl
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"
      - echo Logging in to Amazon ECS...
      - printf '[{"name":"noorapp","imageUri":"805392809179.dkr.ecr.ap-south-1.amazonaws.com/nodre:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
#    - imageDetail.json
    - imagedefinitions.json